apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: playlistshare
    spec:
      containers:
      - name: playlistshare
        image: playlistshare.azurecr.io/playlistshare:latest
        ports:
        - containerPort: 80